name: functional-duality-report
version: 0.1.0.0
synopsis: A Haskell implementation of translations between Distributive Lattices and Priestley Spaces
description: See report.pdf
maintainer: Max Wehmeier <maxwehmi@gmail.com>
category: Logic

ghc-options: -Wall

dependencies:
  - QuickCheck
  - base
  - containers
  - directory
  - lens
  - mtl
  - parsec
  - random
  - template-haskell

library:
  source-dirs: lib

executables:
  duality:
    main: Main.lhs
    source-dirs: exec
    dependencies:
      - functional-duality-report

tests:
  simpletests:
    main: simpletests.lhs
    source-dirs: test
    dependencies:
      - functional-duality-report
      - QuickCheck
      - hspec
